import "server-only";

import { formatRupiah, formatInvoiceDate } from "../../document.utils";
import type { QuotationPdfData } from "../../document.types";
import { SimplePdfDocument, pdfTableRow } from "../pdf-renderer";
import type { PdfTemplate } from "../pdf.types";

export const quotationDefaultTemplate: PdfTemplate<QuotationPdfData> = {
  id: "quotation_default",
  kind: "quotation",
  label: "Quotation default",
  render(data) {
    const doc = new SimplePdfDocument();
    drawHeader(doc, data);
    drawCustomer(doc, data);
    drawItems(doc, data);
    drawTotals(doc, data);
    drawTerms(doc, data);
    return doc.render();
  },
};

function drawHeader(doc: SimplePdfDocument, data: QuotationPdfData) {
  doc.text("OFISSIO", 42, 36, { size: 24, font: "bold", color: "#102a73" });
  doc.text("Workwear & Uniform", 43, 62, { size: 9, font: "bold", color: "#64748b" });
  doc.text("QUOTATION / PENAWARAN", 553, 40, {
    size: 18,
    font: "bold",
    color: "#111827",
    align: "right",
  });
  doc.text(data.isFinal ? "FINAL" : "DRAFT PREVIEW", 553, 62, {
    size: 9,
    font: "bold",
    color: data.isFinal ? "#047857" : "#b45309",
    align: "right",
  });
  doc.line(42, 82, 553, 82, "#dbe3f0");
  doc.cursorY = 100;
}

function drawCustomer(doc: SimplePdfDocument, data: QuotationPdfData) {
  const q = data.quotation;
  doc.rect(42, doc.cursorY, 511, 104, "#f8fafc");
  doc.strokeRect(42, doc.cursorY, 511, 104, "#e2e8f0");
  doc.labelValue({ label: "Quotation no", value: q.quotationNumber, x: 58, y: doc.cursorY + 18, width: 180 });
  doc.labelValue({ label: "Date", value: formatInvoiceDate(q.createdAt), x: 260, y: doc.cursorY + 18, width: 120 });
  doc.labelValue({ label: "Valid until", value: q.validUntil ? formatInvoiceDate(q.validUntil) : "-", x: 410, y: doc.cursorY + 18, width: 120 });
  doc.labelValue({ label: "Company", value: q.companyName, x: 58, y: doc.cursorY + 58, width: 180 });
  doc.labelValue({ label: "PIC", value: `${q.picName} / ${q.picEmail ?? "-"}`, x: 260, y: doc.cursorY + 58, width: 250 });
  doc.cursorY += 126;
}

function drawItems(doc: SimplePdfDocument, data: QuotationPdfData) {
  doc.text("Items", 42, doc.cursorY, { size: 13, font: "bold", color: "#111827" });
  doc.cursorY += 18;
  const widths = [120, 56, 70, 70, 44, 64, 86];
  doc.ensureSpace(60);
  let y = doc.cursorY;
  y += pdfTableRow({
    doc,
    x: 42,
    y,
    widths,
    header: true,
    fill: "#eaf0ff",
    values: ["Produk", "SKU", "Warna", "Size", "Qty", "Harga", "Total"],
  });
  for (const item of data.items) {
    doc.ensureSpace(50);
    if (y > doc.height - 96) {
      doc.addPage();
      y = doc.cursorY;
    }
    y += pdfTableRow({
      doc,
      x: 42,
      y,
      widths,
      values: [
        `${item.productName}\n${item.customizationSummary}`,
        item.sku,
        item.selectedColor,
        item.sizeSummary,
        `${item.totalQty}`,
        item.unitPrice == null ? "-" : formatRupiah(item.unitPrice),
        item.lineTotal == null ? "-" : formatRupiah(item.lineTotal),
      ],
    });
  }
  doc.cursorY = y + 18;
}

function drawTotals(doc: SimplePdfDocument, data: QuotationPdfData) {
  const q = data.quotation;
  doc.ensureSpace(120);
  const x = 330;
  const y = doc.cursorY;
  doc.rect(x, y, 223, 104, "#f8fafc");
  doc.strokeRect(x, y, 223, 104, "#e2e8f0");
  totalRow(doc, "Subtotal", q.subtotal ?? 0, x + 16, y + 16);
  totalRow(doc, "Discount", q.discountTotal, x + 16, y + 34);
  totalRow(doc, "PPN / Tax", q.taxTotal, x + 16, y + 52);
  totalRow(doc, "Ongkir estimasi", q.shippingEstimate, x + 16, y + 70);
  doc.text("Grand total", x + 16, y + 91, { size: 10, font: "bold", color: "#102a73" });
  doc.text(formatRupiah(q.grandTotal ?? 0), x + 207, y + 91, {
    size: 12,
    font: "bold",
    color: "#102a73",
    align: "right",
  });
  doc.cursorY += 128;
}

function totalRow(doc: SimplePdfDocument, label: string, value: number, x: number, y: number) {
  doc.text(label, x, y, { size: 8, color: "#475569" });
  doc.text(formatRupiah(value), x + 190, y, { size: 8, font: "bold", align: "right" });
}

function drawTerms(doc: SimplePdfDocument, data: QuotationPdfData) {
  doc.ensureSpace(150);
  doc.text("Terms", 42, doc.cursorY, { size: 12, font: "bold" });
  let y = doc.cursorY + 18;
  for (const term of data.terms) {
    y += doc.wrappedText(`- ${term}`, 42, y, 500, { size: 8, color: "#334155" });
    y += 3;
  }
  doc.text("Generated by Ofissio system. Internal notes are excluded.", 42, 790, {
    size: 7,
    color: "#64748b",
  });
}
