import type { InternalRole } from "@/lib/security/security.types";

import type { AdminPermission } from "./admin.types";

export const ADMIN_NAV_ITEMS = [
  { href: "/admin", label: "Dashboard" },
  { href: "/admin/products", label: "Produk" },
  { href: "/admin/pricing/embroidery", label: "Harga Bordir" },
  { href: "/admin/quotations", label: "Quotations" },
  { href: "/admin/orders", label: "Orders" },
  { href: "/admin/notifications", label: "Notifikasi" },
  { href: "/admin/settings/email", label: "Email" },
  { href: "/admin/process-orders", label: "Process Orders" },
  { href: "/admin/shipments", label: "Shipments" },
  { href: "/admin/customers", label: "Customers" },
  { href: "/admin/catalog", label: "Catalog" },
  { href: "/admin/uploads", label: "Uploads / Logos" },
  { href: "/admin/tracking", label: "Tracking" },
  { href: "/admin/audit", label: "Audit" },
] as const;

export const ADMIN_ROLE_PERMISSIONS: Record<InternalRole, AdminPermission[]> = {
  super_admin: [
    "admin:view",
    "admin:quotation:view",
    "admin:quotation:update",
    "admin:order:view",
    "admin:order:update",
    "admin:process-order:view",
    "admin:process-order:update",
    "admin:shipment:view",
    "admin:shipment:update",
    "admin:tracking:view",
    "admin:tracking:update",
    "admin:upload:view",
    "admin:customer:view",
    "admin:catalog:view",
    "admin:catalog:update",
    "admin:notification:view",
    "admin:notification:update",
    "admin:email:view",
    "admin:email:test",
    "admin:audit:view",
  ],
  sales: [
    "admin:view",
    "admin:quotation:view",
    "admin:quotation:update",
    "admin:order:view",
    "admin:order:update",
    "admin:process-order:view",
    "admin:process-order:update",
    "admin:shipment:view",
    "admin:shipment:update",
    "admin:upload:view",
    "admin:customer:view",
    "admin:catalog:view",
    "admin:notification:view",
    "admin:notification:update",
    "admin:email:view",
    "admin:email:test",
  ],
  finance_internal: ["admin:view", "admin:quotation:view", "admin:order:view", "admin:order:update", "admin:process-order:view", "admin:shipment:view"],
  product_admin: [
    "admin:view",
    "admin:upload:view",
    "admin:customer:view",
    "admin:catalog:view",
    "admin:catalog:update",
    "admin:notification:view",
    "admin:notification:update",
  ],
  production_admin: [
    "admin:view",
    "admin:order:view",
    "admin:order:update",
    "admin:process-order:view",
    "admin:process-order:update",
    "admin:shipment:view",
    "admin:shipment:update",
    "admin:tracking:view",
    "admin:tracking:update",
    "admin:upload:view",
    "admin:catalog:view",
  ],
  ppic: ["admin:view", "admin:order:view", "admin:process-order:view", "admin:process-order:update", "admin:shipment:view", "admin:tracking:view", "admin:tracking:update"],
  qc: ["admin:view", "admin:order:view", "admin:process-order:view", "admin:process-order:update", "admin:shipment:view", "admin:tracking:view", "admin:tracking:update"],
  logistics: ["admin:view", "admin:order:view", "admin:process-order:view", "admin:process-order:update", "admin:shipment:view", "admin:shipment:update", "admin:tracking:view", "admin:tracking:update"],
  support: [
    "admin:view",
    "admin:quotation:view",
    "admin:order:view",
    "admin:process-order:view",
    "admin:shipment:view",
    "admin:tracking:view",
    "admin:upload:view",
    "admin:customer:view",
    "admin:catalog:view",
    "admin:audit:view",
  ],
};

export const ADMIN_QUOTATION_UPDATE_STATUSES = [
  "submitted",
  "under_review",
  "quoted",
  "revision_requested",
  "accepted",
  "rejected",
  "expired",
  "cancelled",
] as const;
