import type { InternalRole } from "@/lib/security/security.types";

import type { AdminPermission } from "./admin.types";

export const ADMIN_NAV_ITEMS = [
  { href: "/admin", label: "Dashboard", permission: "admin:view" },
  { href: "/admin/products", label: "Produk", permission: "admin:catalog:view" },
  { href: "/admin/pricing/embroidery", label: "Harga Bordir", permission: "admin:catalog:view" },
  { href: "/admin/settings/tax", label: "PPN", permission: "admin:tax:view" },
  { href: "/admin/quotations", label: "Quotations", permission: "admin:quotation:view" },
  { href: "/admin/orders", label: "Orders", permission: "admin:order:view" },
  { href: "/admin/notifications", label: "Notifikasi", permission: "admin:notification:view" },
  { href: "/admin/settings/email", label: "Email", permission: "admin:email:view" },
  { href: "/admin/process-orders", label: "Process Orders", permission: "admin:process-order:view" },
  { href: "/admin/shipments", label: "Shipments", permission: "admin:shipment:view" },
  { href: "/admin/customers", label: "Customers", permission: "admin:customer:view" },
  { href: "/admin/catalog", label: "Catalog", permission: "admin:catalog:view" },
  { href: "/admin/uploads", label: "Uploads / Logos", permission: "admin:upload:view" },
  { href: "/admin/tracking", label: "Tracking", permission: "admin:tracking:view" },
  { href: "/admin/integrations/ginee", label: "Ginee", permission: "admin:integration:ginee:view" },
  { href: "/admin/audit", label: "Audit", permission: "admin:audit:view" },
] as const;

export const ADMIN_ROLE_PERMISSIONS: Record<InternalRole, AdminPermission[]> = {
  super_admin: [
    "admin:access",
    "admin:view",
    "admin:quotation:convert",
    "admin:quotation:view",
    "admin:quotation:update",
    "admin:order:view",
    "admin:order:update",
    "admin:payment:view",
    "admin:payment:create",
    "admin:invoice:view",
    "admin:invoice:send",
    "admin:product:view",
    "admin:product:update",
    "admin:settings:view",
    "admin:settings:update",
    "admin:process-order:view",
    "admin:process-order:update",
    "admin:shipment:view",
    "admin:shipment:update",
    "admin:tracking:view",
    "admin:tracking:update",
    "admin:upload:view",
    "admin:customer:view",
    "admin:catalog:view",
    "admin:catalog:update",
    "admin:notification:view",
    "admin:notification:update",
    "admin:email:view",
    "admin:email:test",
    "admin:tax:view",
    "admin:tax:update",
    "admin:integration:ginee:view",
    "admin:integration:ginee:update",
    "admin:integration:ginee:sync_read",
    "admin:audit:view",
  ],
  sales_admin: [
    "admin:access", "admin:view", "admin:quotation:view", "admin:quotation:update",
    "admin:quotation:convert", "admin:order:view", "admin:order:update",
    "admin:payment:view", "admin:payment:create", "admin:invoice:view",
    "admin:invoice:send", "admin:notification:view", "admin:notification:update",
    "admin:customer:view", "admin:catalog:view",
    "admin:integration:ginee:view", "admin:integration:ginee:sync_read",
  ],
  finance_admin: [
    "admin:access", "admin:view", "admin:quotation:view", "admin:order:view",
    "admin:payment:view", "admin:payment:create", "admin:invoice:view",
    "admin:invoice:send", "admin:tax:view", "admin:tax:update",
    "admin:settings:view", "admin:settings:update",
  ],
  sales: [
    "admin:view",
    "admin:quotation:view",
    "admin:quotation:update",
    "admin:order:view",
    "admin:order:update",
    "admin:process-order:view",
    "admin:process-order:update",
    "admin:shipment:view",
    "admin:shipment:update",
    "admin:upload:view",
    "admin:customer:view",
    "admin:catalog:view",
    "admin:notification:view",
    "admin:notification:update",
    "admin:email:view",
    "admin:email:test",
    "admin:tax:view",
    "admin:integration:ginee:view",
    "admin:integration:ginee:sync_read",
  ],
  finance_internal: ["admin:view", "admin:quotation:view", "admin:order:view", "admin:order:update", "admin:process-order:view", "admin:shipment:view", "admin:tax:view", "admin:tax:update"],
  product_admin: [
    "admin:view",
    "admin:upload:view",
    "admin:customer:view",
    "admin:catalog:view",
    "admin:catalog:update",
    "admin:notification:view",
    "admin:notification:update",
    "admin:integration:ginee:view",
    "admin:integration:ginee:update",
    "admin:integration:ginee:sync_read",
  ],
  production_admin: [
    "admin:view",
    "admin:order:view",
    "admin:order:update",
    "admin:process-order:view",
    "admin:process-order:update",
    "admin:shipment:view",
    "admin:shipment:update",
    "admin:tracking:view",
    "admin:tracking:update",
    "admin:upload:view",
    "admin:catalog:view",
    "admin:integration:ginee:view",
    "admin:integration:ginee:sync_read",
  ],
  ppic: ["admin:view", "admin:order:view", "admin:process-order:view", "admin:process-order:update", "admin:shipment:view", "admin:tracking:view", "admin:tracking:update", "admin:integration:ginee:view", "admin:integration:ginee:sync_read"],
  qc: ["admin:view", "admin:order:view", "admin:process-order:view", "admin:process-order:update", "admin:shipment:view", "admin:tracking:view", "admin:tracking:update"],
  logistics: ["admin:view", "admin:order:view", "admin:process-order:view", "admin:process-order:update", "admin:shipment:view", "admin:shipment:update", "admin:tracking:view", "admin:tracking:update", "admin:integration:ginee:view", "admin:integration:ginee:sync_read"],
  support: [
    "admin:view",
    "admin:quotation:view",
    "admin:order:view",
    "admin:process-order:view",
    "admin:shipment:view",
    "admin:tracking:view",
    "admin:upload:view",
    "admin:customer:view",
    "admin:catalog:view",
    "admin:audit:view",
    "admin:integration:ginee:view",
    "admin:integration:ginee:sync_read",
  ],
};

export const ADMIN_QUOTATION_UPDATE_STATUSES = [
  "submitted",
  "under_review",
  "expired",
  "cancelled",
] as const;
